service: face-auth

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
resources:
  Resources:
    user:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        TableName: user
        AttributeDefinitions:
          - AttributeName: faceId
            AttributeType: S
        KeySchema:
          - AttributeName: faceId
            KeyType: HASH
        ProvisionedThroughput:
          WriteCapacityUnits: 1
          ReadCapacityUnits: 1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      migrate: true